---
yc_hosts:
  - name: clickhouse-01
    hostname: clickhouse-01
    group: clickhouse
    zone: ru-central1-a
    platform_id: standard-v3
    cores: 2
    memory: 4
    core_fraction: 20
    image_family: rocky-linux-9
    nat: true
    subnet_id: "<SUBNET_ID>"
    ssh_user: "kva"
    public_key_path: "~/.ssh/id_ed25519.pub"
    vm_state: running

  - name: vector-01
    hostname: vector-01
    group: vector
    zone: ru-central1-a
    platform_id: standard-v3
    cores: 2
    memory: 2
    core_fraction: 20
    image_family: rocky-linux-9
    nat: true
    subnet_id: "<SUBNET_ID>"
    ssh_user: "kva"
    public_key_path: "~/.ssh/id_ed25519.pub"
    vm_state: running

  - name: lighthouse-01
    hostname: lighthouse-01
    group: lighthouse
    zone: ru-central1-a
    platform_id: standard-v3
    cores: 2
    memory: 2
    core_fraction: 20
    image_family: rocky-linux-9
    nat: true
    subnet_id: "<SUBNET_ID>"
    ssh_user: "kva"
    public_key_path: "~/.ssh/id_ed25519.pub"
    vm_state: running